### ISSUE TITLE
com.aric.myfm.domain.User -- FetchType.LAZY Error

### ISSUE THREAD

**Issue by erdkse** [dursunkoc/myfm#1]
Hi i am planning to make an api by using your project. But there is an issue with data fetching type. If i use 'FetchType.Lazy' between linked(manyToMany,oneToMany) entities the app gives me 
# failed to lazily initialize a collection of role: com.aric.myfm.domain.User.roles, could not initialize proxy - no Session

 error. I think it is about hibernate session but i dont know how to configure it via Spring Framework. Could you add this configuration please? I need it a lot.

**Comment by dursunkoc** [comment]
I just could not understand your point, i have reloaded the application and it just work as i expected without any error. can you provide an exception stacktrace?

**Comment by erdkse** [comment]
I meant i created new entity classes whichs are linked each other. They run into problem. If you change fethType of 'Set<String> roles' to LAZY in com.aric.myfm.domain.User. You will face with the same problem.

These are my entity classes I added to your project:
https://gist.github.com/erdkse/ae16160a22ab3fab89e1
https://gist.github.com/erdkse/7d12b9cc423290578329

You may want to add these classes to your project as they are and insert some values than try to get a Company entity. You will get the error I'm facing. Or just retype the 'roles' variables fecthType to Lazy you will see the problem again. In my opinion changing fetchType shouldn't cause a problem but in your project it does. I couldn't figure out why and that is why just asked you. 

Thank you for your attention.
